### ISSUE TITLE
missing script: start

### ISSUE THREAD

**Issue by rahulrkr08** [deric/docker-nodejs-helloworld#1]
I am getting below error when I am deploying this application on Openshift.

Environment:
--
  | DEV_MODE=false
  | NODE_ENV=production
  | DEBUG_PORT=5858
  | Launching via npm...
  | npm info it worked if it ends with ok
  | npm info using npm@2.15.1
  | npm info using node@v4.6.2
  | npm ERR! Linux 3.10.0-693.15.2.el7.x86_64
  | npm ERR! argv "/opt/rh/rh-nodejs4/root/usr/bin/node" "/opt/rh/rh-nodejs4/root/usr/bin/npm" "run" "-d" "start"
  | npm ERR! node v4.6.2
  | npm ERR! npm  v2.15.1
  |  
  | npm ERR! missing script: start
  | npm ERR!
  | npm ERR! If you need help, you may report this error at:
  | npm ERR!     <https://github.com/npm/npm/issues>
  |  
  | npm ERR! Please include the following file with any support request:
  | npm ERR!     /opt/app-root/src/npm-debug.log

**Comment by deric** [comment]
Resolved by #2.
